# Generated by Django 5.2.6 on 2025-09-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('startup', '0002_alter_startupprofile_logo_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requirements_file',
            field=models.URLField(blank=True, help_text='Supabase URL for requirements document', null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='employees_assigned',
        ),
        migrations.AddField(
            model_name='project',
            name='employees_assigned',
            field=models.ManyToManyField(blank=True, related_name='projects', to='startup.employee'),
        ),
    ]
