# Generated by Django 5.2.6 on 2025-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_startups', models.PositiveIntegerField(default=0)),
                ('total_freelancers', models.PositiveIntegerField(default=0)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('total_funding', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
