# Generated by Django 5.2.6 on 2025-09-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipsession',
            name='topic',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
